# Generated by Django 5.2.10 on 2026-01-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='fullname',
            field=models.CharField(default='wuming', max_length=500),
            preserve_default=False,
        ),
    ]
