# Generated by Django 5.2.10 on 2026-01-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_appuser_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
