# Generated by Django 5.2.10 on 2026-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_fullname_appuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='appuser',
            name='agent_status',
            field=models.BooleanField(default=False),
        ),
    ]
