# Generated by Django 5.2.10 on 2026-01-12 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_appuser_location_remove_appuser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('nin_number', models.CharField(max_length=11)),
                ('years_of_experience', models.CharField(max_length=32)),
                ('id_file', models.FileField(upload_to='id_files')),
                ('license_file', models.FileField(upload_to='licence_files')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
