# Generated by Django 5.2.10 on 2026-01-16 05:21

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_agentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=400)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', Main.models.AppUserManager()),
            ],
        ),
    ]
