# Generated by Django 5.2.10 on 2026-01-16 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_contactrequest_alter_appuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease'), ('shortLet', 'ShortLet'), ('land', 'Land')], max_length=60)),
                ('size', models.IntegerField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('swimming_pool', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('borehole', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('serviced', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.property')),
            ],
        ),
    ]
