# Generated by Django 5.2.10 on 2026-01-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_property_propertyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='no_of_bathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
