# Generated by Django 5.2.10 on 2026-01-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_property_no_of_bathrooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImages',
            new_name='PropertyImage',
        ),
    ]
